version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-
      - run: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn mklib build
      - run: yarn mklib test
      - run: yarn mklib lint
